load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "mock-vfprintf",
    srcs = ["mock-vfprintf.cc"],
    hdrs = ["mock-vfprintf.h"],
    visibility = ["//test/src:__pkg__"],
)

cc_library(
    name = "mock-fprintf",
    srcs = ["mock-fprintf.cc"],
    hdrs = ["mock-fprintf.h"],
    visibility = ["//test/src:__pkg__"],
)

cc_library(
    name = "mock-vsyslog",
    srcs = ["mock-vsyslog.cc"],
    hdrs = ["mock-vsyslog.h"],
    visibility = ["//test/src:__pkg__"],
)